services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      # Port on your host machine : Port inside the container
      - "8594:80"
    volumes:
      # This is where your uploaded files will be stored.
      # './my-data' will be a folder created next to your docker-compose file.
      - ./my-data:/srv

      # This stores the File Browser configuration and user database.
      - ./filebrowser.db:/database/filebrowser.db
    environment:
      # Sets the base URL if you access it through a subdirectory (optional)
      - FB_BASEURL=/filebrowser/
