---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- System:
    - Cpu:
        icon: glances.png
        widget:
            type: glances
            url: http://glances:61208   # Changed 'monitoring' to 'glances'
            metric: cpu
            version: 4                  # Added version 4
    - Sensor:
        icon: glances.png
        widget:
            type: glances
            url: http://glances:61208   # Changed 'monitoring' to 'glances'
            metric: sensor:Package id 0
            version: 4                  # Added version 4
    - Memory:
        icon: glances.png
        widget:
            type: glances
            url: http://glances:61208   # Changed 'monitoring' to 'glances'
            metric: memory
            version: 4                  # Added version 4
    - Process:
        icon: glances.png
        widget:
            type: glances
            url: http://glances:61208   # Changed 'monitoring' to 'glances'
            metric: process
            version: 4                  # Added version 4
    - Network:
        icon: glances.png
        widget:
            type: glances
            url: http://glances:61208   # Changed 'monitoring' to 'glances'
            metric: network:eth0
            version: 4                  # Added version 4



- Home Server:
    - FritzBox:
        icon: fritzbox.png
        href: http://fritz.box/
        widget:
            type: fritzbox
            url: http://fritz.box/
    - StirlingPDF:
        icon: stirlingpdf.png
        href: ${STIRLING_PDF_URL}
        description: StirlingPDF
    - Immich Tools:
        icon: immich.png
        href: ${IMMICH_POWERTOOLS_URL}
        description: PowerTools for Immich
