---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: {{HOMEPAGE_VAR_TITLE}}

headerStyle: {{HOMEPAGE_VAR_HEADER_STYLE}}

layout:
  Media:
    style: row
    columns: 5
  Download:
    style: row
    columns: 3
  Home Server:
    style: column
    rows: 2
  Utilities:
    style: column
    rows: 2
  System:
    style: row
    columns: 3

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true
